[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "cctv-attendance-api"

[services.variables]
NODE_ENV = "production"
PORT = "5000"
MONGODB_URI = "${{MONGODB_URI}}"
JWT_SECRET = "${{JWT_SECRET}}"
EMAIL_USER = "${{EMAIL_USER}}"
EMAIL_PASS = "${{EMAIL_PASS}}"
SMTP_HOST = "${{SMTP_HOST}}"
SMTP_PORT = "${{SMTP_PORT}}"
